config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => "/cable"

  namespace :admin do
    resources :users
    resources :objs
    resources :categories
  end


  # namespace :api, path: 'somthing' do => /something => api::xxx
  namespace :api, path: '' do
    constraints(host: 'api.localhost') do
      resources :users
    end
  end  

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    collection do
      get :edit_collection
      get :edit_like
      get :edit_subscribe
      get :edit_friendship
      get :show_friends
    end
  end

  resources :user_comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "objs#index"

  resources :objs do
    collection do
      post :post_index 
      get :editor
      get :about
    end
  end

  resources :tags
end

app/models/obj.rb
class Obj < ApplicationRecord
	validates_presence_of :name
	validates_uniqueness_of :serial
	validates :datebought, format: { with: /\d{4}-\d{2}-\d{2}/, message: "format should be: yyyy-mm-dd" }
	validates :dateretire, format: { with: /\d{4}-\d{2}-\d{2}/, message: "format should be: yyyy-mm-dd" }
	validates_numericality_of :value, :only_integer => true # 必須是整數
  validates_numericality_of :access_authority, :only_integer => true, :greater_than => 0, :less_than => 5
	validates_presence_of :description

  belongs_to :user

  has_many :public_comments, ->{ where( "ispublic = ?", true)},:dependent => :destroy, :class_name => 'Comment'
  has_many :comments, :dependent => :destroy

  has_many :obj_categoryships, :dependent => :destroy
  has_many :categories, :through => :obj_categoryships

  has_many :user_collectionships, :dependent => :destroy
  has_many :user_likeships, :dependent => :destroy
  has_many :user_subscribeships, :dependent => :destroy

  has_many :tags, :through => :obj_tagships
  has_many :obj_tagships, :dependent => :destroy

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/system/objs/images/:style/鮮乳坊簽名圖.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/views/admin/_categories.html.erb
<% count_if_no_objs = nil %>

<div class="panel panel-info">
  <!-- Default panel contents -->
  <div class="panel-heading">
    <h1>Category List</h1>
  </div>
  <div class="panel-body">
    <div class="btn-group btn-group-justified" role="group" aria-label="...">
      <%= form_tag admin_categories_path do %>
        <% Category.includes(:obj_categoryships).each do |category| %>
          <div class="btn-group" role="group">
            <% if category.obj_categoryships.length == 0 %>
              <% count_if_no_objs = true %>
              <div class="input-group">
                <span class="input-group-addon">
                  <%= check_box_tag "category_ids[]", category.id, false %>
                </span>
                <div class="input-group-btn">
                  <%= link_to category.name, edit_admin_category_path(category), :class => "btn btn-warning"  %>
                </div>
              </div>
            <% else %>
              <%= link_to category.name, edit_admin_category_path(category), :class => "btn btn-default"  %>
            <% end %>
          </div>
        <% end %>
        <% if count_if_no_objs %>
          <div class="btn-group" role="group">
            <%= submit_tag "Del", :class => "btn btn-danger" %>
          </div>
        <% end %>
      <% end %>
      <%= hidden_field_tag 'category_ids[]','' %>    
    </div>
  </div>

  <div class="panel-body">
    <%= render :partial => "admin/form_category" %>
  </div>
</div>

app/views/admin/_form_category.html.erb
<% if @category.new_record? %>
  <% url = admin_categories_path %>
  <% btn_name = "Create!" %>
  <% class_details = "btn-success" %>
<% else %>
  <% url = admin_category_path(@category) %>
  <% btn_name = "Update!" %>
  <% class_details = "btn-primary" %>
<% end %>

<%= form_for @category, :url => url do |f| %>
  <div class="input-group">
    <span class="input-group-btn">
        <button class="btn <%= class_details %>" type="submit"><%= btn_name %></button>
    </span>
    <%= f.text_field :name, :class=>"form-control", :placeholder => "Category..." %>
  </div>
<% end %>