config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => "/cable"

  namespace :admin do
    resources :users
    resources :objs
    resources :categories
  end


  # namespace :api, path: 'somthing' do => /something => api::xxx
  namespace :api, path: '' do
    constraints(host: 'api.localhost') do
      resources :users
    end
  end  

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    collection do
      get :edit_collection
      get :edit_like
      get :edit_subscribe
      get :edit_friendship
      get :show_friends
    end
  end

  resources :user_comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "objs#index"

  resources :objs do
    collection do
      post :post_index 
      get :editor
      get :about
    end
  end

  resources :tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :objs, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :user_collectionships, :dependent => :destroy
  has_many :user_likeships, :dependent => :destroy
  has_many :user_subscribeships, :dependent => :destroy
  has_many :userships, :dependent => :destroy
  serialize :fb_raw_data
  
  def self.from_omniauth(auth)
    # Case 1: Find existing user by facebook uid
    user = User.find_by_fb_uid( auth.uid )
    if user
      user.fb_token = auth.credentials.token
      user.fb_name = auth.info.name
      user.fb_avatar = auth.info.image
      user.fb_raw_data = auth
      user.save!
      return user
    end

    # Case 2: Find existing user by email
    existing_user = User.find_by_email( auth.info.email )
    if existing_user
      existing_user.fb_uid = auth.uid
      existing_user.fb_token = auth.credentials.token
      existing_user.fb_name = auth.info.name
      user.fb_avatar = auth.info.image
      existing_user.fb_raw_data = auth
      existing_user.save!
      return existing_user
    end

    # Case 3: Create new password
    user = User.new
    user.fb_uid = auth.uid
    user.fb_token = auth.credentials.token
    user.fb_name = auth.info.name
    user.fb_avatar = auth.info.image
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.fb_raw_data = auth
    user.save!
    return user
  end
  
  def admin?
    self.role == "admin" 
  end
  def access?(target)
    self.admin? || self == target.user
  end
  def see?(target)
    self.admin? || target.ispublic
  end
  def have_new_friend?
    added_me_arr = Usership.where(:friend_id => self.id).pluck(:user_id)
    my_friends_arr = self.userships.pluck(:friend_id)
    (added_me_arr&my_friends_arr) != added_me_arr
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminApplicationController
  before_action :find_user, :only => [:edit, :update, :destroy]

  def index
    @users = User.all
    @users = @users.page(params[:page]).per(10)
    if params[:category_id]
      @category = Category.find(params[:category_id])
    else
      @category = Category.new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user.update(user_params)
    flash[:notice] = "successful updated " + @user.email + " informations."
    redirect_to admin_users_path
  end

  def destroy
    flash[:warning] = "successful deleted " + @user.email
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :nickname, :firstname, :lastname, :role)
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::BaseController
  # skip_befor_action_auth_for_devise(postman_testing)
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!

  #rescue_from (class)=> Ac_R_::R_N_F.. , with def somthing(e)=> e.message...do_something... => render json:....

  def index
    @users = User.all
    # response.headers['Content-Typea'] = 'abcdefg'
    # render json: { users: @users }
    # (想要customize的話請愛用prefix)
  end

  def show
    @user = User.find(params[:id])
    # render json: { user: @user }
  end

  def create
    @user = User.new(params.require(:user).permit(:email, :password))
    if @user.save
      render json: { user: @user }
    else
      render json: { errors: @user.errors.full_messages }, status: 402
    end
  end

  def update
    @user = User.find(params[:id])
    render json: { user: @user }
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  helper_method :friend?, :friend_of_him?

  def show
    @user = User.find(params[:id])

    user_collection_arr = UserCollectionship.where(:user_id => params[:id]).pluck(:obj_id)
    @user_collection_objs = Obj.includes(:user).where(:id => user_collection_arr)

    user_like_arr = UserLikeship.where(:user_id => params[:id]).pluck(:obj_id)
    @user_like_objs = Obj.where(:id => user_like_arr)

    @user_comments = @user.comments.includes(:obj)
    @user_objs = @user.objs.includes(:public_comments)
  end
  def edit_collection
    @obj = Obj.find(params[:obj_id])
    @user_collectionship = current_user.user_collectionships.find_by_obj_id(@obj)
    if @user_collectionship
      @user_collectionship.destroy
    else
      UserCollectionship.create(:user_id => current_user.id, :obj_id  => @obj.id)
    end
    respond_to do |format|
      format.js
    end
  end
  def edit_like
    @obj = Obj.find(params[:obj_id])
    @user_likeship = current_user.user_likeships.find_by_obj_id(@obj)
    if @user_likeship
      @user_likeship.destroy
      @user_likeship_arr = nil
    else
      UserLikeship.create(:user_id => current_user.id, :obj_id  => @obj.id)
      @user_likeship_arr = [params[:obj_id].to_i]
    end
    respond_to do |format|
      format.js
    end
  end
  def edit_subscribe
    @obj = Obj.find(params[:obj_id])
    @user_subscribeship = current_user.user_subscribeships.find_by_obj_id(@obj)
    if @user_subscribeship
      @user_subscribeship.destroy
    else
      UserSubscribeship.create(:user_id => current_user.id, :obj_id  => @obj.id)
    end
    respond_to do |format|
      format.js
    end
  end
  def edit_friendship
    @friend = User.find(params[:friend_id])
    if friend?(@friend)
      Usership.find_by_user_id_and_friend_id(current_user.id, @friend.id).destroy
    else
      Usership.create(:user=>current_user,:friend_id=>@friend.id)
    end
    respond_to do |format|
      format.js
      format.html { redirect_to show_friends_users_path }
    end
  end
  def show_friends
    @user = current_user
    my_friends_arr = @user.userships.pluck(:friend_id)
    added_me_arr = Usership.where(:friend_id => @user.id).pluck(:user_id)
    requests_arr = added_me_arr - (added_me_arr&my_friends_arr) if (added_me_arr&my_friends_arr) != added_me_arr
    @my_friends = User.where(:id => my_friends_arr)
    @friend_requests = User.where(:id => requests_arr)
  end
  def friend?(friend)
    current_user.userships.find_by_friend_id(friend).present?
  end
  def friend_of_him?(friend)
    friend.userships.find_by_friend_id(current_user.id)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_collection.html.erb
<% if collected?(@obj) %>
  <% class_of_collect_link = "btn glyphicon glyphicon-heart" %>
<% else %>
  <% class_of_collect_link = "btn glyphicon glyphicon-heart-empty" %>
<% end %>
<%= link_to "", edit_collection_users_path(:obj_id => @obj.id), :class => class_of_collect_link, :remote => true %>

app/views/users/_friend_request.html.erb
<% if friend?(friend) %>
  <% if friend.userships.find_by_friend_id(current_user).present? %>
    <%= content_tag(:span, " Friend",:class => "btn btn-default glyphicon glyphicon-ok") %>
  <% else %>
    <%= link_to "request sent", edit_friendship_users_path(:friend_id => friend), :class => "btn btn-default active", :remote => true %>
  <% end %>
<% else %>
  <%= link_to "send request", edit_friendship_users_path(:friend_id => friend), :class => "btn btn-default" , :remote => true %>
<% end %>

app/views/users/_like.html.erb
<% if liked?(obj) %>
  <% class_of_like_link = "btn glyphicon glyphicon-star" %>
<% else %>
  <% class_of_like_link = "btn glyphicon glyphicon-star-empty" %>
<% end %>
<%= link_to obj.user_likeships.size, edit_like_users_path(:obj_id => obj.id), :class => class_of_like_link, :remote => true %>

app/views/users/_subscribe.html.erb
<% if subscribed?(@obj) %>
  <% class_of_subscribe_link = "glyphicon glyphicon-ok" %>
  <% class_of_subscribe_buttun = "btn btn-success" %>
  <% name_of_buttun = " Subscribed" %>
<% else %>
  <% class_of_subscribe_link = "glyphicon glyphicon-plus" %>
  <% class_of_subscribe_buttun = "btn btn-primary" %>
  <% name_of_buttun = " Subscribe!" %>
<% end %>
<%= link_to edit_subscribe_users_path(:obj_id => @obj.id), :class => class_of_subscribe_buttun, :remote => true do %>
  <%= content_tag(:span, name_of_buttun,:class => class_of_subscribe_link) %>
<% end %>

app/views/users/edit.js.erb
var content = "<%= j render(:partial=>'like', :locals => {:obj => @obj}) %>"
$('#like_star_<%= params[:id] %>').html(content);

app/views/users/edit_collection.js.erb
var content = "<%= j render(:partial=>'collection') %>"
$('#collection_heart').html(content);

app/views/users/edit_friendship.js.erb
var content = "<%=j render(:partial=>'friend_request', :locals => {:friend => @friend}) %>"
$('#friend_request').html(content);

app/views/users/edit_like.js.erb
var content = "<%= j render(:partial=>'like', :locals => {:obj => @obj}) %>"
$('#like_star_<%= params[:obj_id] %>').html(content);

app/views/users/edit_subscribe.js.erb
var content = "<%= j render(:partial=>'subscribe') %>"
$('#subscribe_buttun').html(content);

app/views/users/show.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">
    <div id="friend_request" class="pull-right">
      <%= render :partial => "friend_request", :locals => {:friend => @user} unless current_user == @user %>
    </div>
    <h1><%= user_name(@user) %></h1>
  </div>

  <!-- Table -->
  <table class="table table-bordered table-striped">
    <tr>
      <th></th>
      <th>內容</th>
    </tr>
    <tr>
      <td class="text-capitalize align-right col-md-2">objs</td>
      <td>
        <% @user_objs.each do |obj| %>
          <ul class="pager">
            <li class="previous">
              <%= link_to obj_link(obj), data: { turbolinks: false } do %>
                <% if obj.ispublic %>
                  <%= obj.name %>
                  <span aria-hidden="true">&rarr;</span>
                <% else %>
                  <%= "(Draft...) " + obj.name %>
                <% end %>
              <% end %>
            </li>
          </ul>
          <% obj.comments.each do |obj_comment| %>
            <div class="panel panel-primary">
              <div class="panel-heading"><%= obj_comment.title %></div>
              <div class="panel-body"><%= obj_comment.paragraph %></div>
            </div>
          <% end %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td class="text-capitalize align-right col-md-2">comments</td>
      <td>
        <% @user_comments.each do |comment| %>
          <ul class="pager">
            <li class="previous">
              <%= link_to obj_path(comment.obj) do %>
                <span aria-hidden="true">&larr;</span>
                <%= comment.obj[:name] %>
              <% end %>
            </li>
          </ul>
          <div class="panel panel-default">
            <div class="panel-heading"><%= comment.title %></div>
            <div class="panel-body"><%= comment.paragraph %></div>
          </div>
        <% end %>
      </td>
    </tr>
    <tr>
      <td class="text-capitalize align-right col-md-2">nickname</td>
      <td class="col-md-10 text-left"><%= @user.nickname %></td>
    </tr>
    <tr>
      <td class="text-capitalize align-right col-md-2">email</td>
      <td class="col-md-10 text-left"><%= @user.email %></td>
    </tr>
    <tr>
      <td class="text-capitalize align-right col-md-2">collection</td>
      <td>
        <% @user_collection_objs.each do |collection_obj| %>
          <%= link_to obj_path(collection_obj) do %>
            <span aria-hidden="true">&larr;</span>
            <%= collection_obj.name %>
          <% end %>
          <div class="panel panel-info">
            <div class="panel-heading">
              <%= user_name(collection_obj.user) %>
            </div>
            <div class="panel-body"><%= collection_obj.description %></div>
          </div>
        <% end %>
      </td>
    </tr>
    <tr>
      <td class="text-capitalize align-right col-md-2">liked</td>
      <td>-
        <% @user_like_objs.each do |like_obj| %>
          <%= like_obj.name %> -
        <% end %>
      </td>
    </tr>
  </table>
</div>

<%= link_to "Index", objs_path, :class => "btn btn-default" %>

app/views/users/show_friends.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">
    <h1>Friends</h1>
  </div>
  <% if @friend_requests.present? %>
    <div class="panel-body">
      <h3>Friend requests:</h3></br>
      <% @friend_requests.each do |requestfriend| %>
      <div class="col-md-3">
        <div class="input-group">
          <span class="input-group-btn">
            <%= link_to "confirm request", edit_friendship_users_path(:friend_id => requestfriend.id), :class => "btn btn-default", data: { turbolinks: false } %>
          </span>
          <span class="form-control text-center" style="margin-left: -1px;">
            <%= link_to user_name(requestfriend), user_path(requestfriend), :class => "btn-link" %>
          </span>
        </div>
      </div>
      <% end %>
    </div>
  <% end %>

  <!-- Table -->
  <table class="table table-hover">
    <th>
      <td>Status</td>
      <td>Email</td>
      <td>Sign_in_count</td>
      <td>Last_sign_in_at</td>
      <td>Created_at</td>
    </th>
    <% @my_friends.each do |myfriend| %>
      <tr id="friend_<%= myfriend.id %>">
        <td>
          <%= link_to "", edit_friendship_users_path(:friend_id => myfriend.id), 
            :class => "btn btn-danger hidden glyphicon glyphicon-remove", 
            :id => "delete_#{myfriend.id}", :style => "top:0;", :remote => "true", :method => "delete" %>
          <%= link_to user_name(myfriend), user_path(myfriend), :class => "btn btn-default" %>
        </td>
        <td>
          <%= content_tag(
          :p, friend_of_him?(myfriend) ? "friend" : "request sent", 
          :style => "margin: 0;line-height:3rem;") %>
        </td>
        <td><%= content_tag(:p, myfriend.email, :style => "margin: 0;line-height:3rem;") %></td>
        <td><%= content_tag(:p, myfriend.sign_in_count, :style => "margin: 0;line-height:3rem;") %></td>
        <td><%= content_tag(:p, myfriend.last_sign_in_at, :style => "margin: 0;line-height:3rem;") %></td>
        <td><%= content_tag(:p, myfriend.created_at, :style => "margin: 0;line-height:3rem;") %></td>
      </tr>
    <% end %>
  </table>
</div>