config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => "/cable"

  namespace :admin do
    resources :users
    resources :objs
    resources :categories
  end


  # namespace :api, path: 'somthing' do => /something => api::xxx
  namespace :api, path: '' do
    constraints(host: 'api.localhost') do
      resources :users
    end
  end  

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    collection do
      get :edit_collection
      get :edit_like
      get :edit_subscribe
      get :edit_friendship
      get :show_friends
    end
  end

  resources :user_comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "objs#index"

  resources :objs do
    collection do
      post :post_index 
      get :editor
      get :about
    end
  end

  resources :tags
end

app/models/obj.rb
class Obj < ApplicationRecord
	validates_presence_of :name
	validates_uniqueness_of :serial
	validates :datebought, format: { with: /\d{4}-\d{2}-\d{2}/, message: "format should be: yyyy-mm-dd" }
	validates :dateretire, format: { with: /\d{4}-\d{2}-\d{2}/, message: "format should be: yyyy-mm-dd" }
	validates_numericality_of :value, :only_integer => true # 必須是整數
  validates_numericality_of :access_authority, :only_integer => true, :greater_than => 0, :less_than => 5
	validates_presence_of :description

  belongs_to :user

  has_many :public_comments, ->{ where( "ispublic = ?", true)},:dependent => :destroy, :class_name => 'Comment'
  has_many :comments, :dependent => :destroy

  has_many :obj_categoryships, :dependent => :destroy
  has_many :categories, :through => :obj_categoryships

  has_many :user_collectionships, :dependent => :destroy
  has_many :user_likeships, :dependent => :destroy
  has_many :user_subscribeships, :dependent => :destroy

  has_many :tags, :through => :obj_tagships
  has_many :obj_tagships, :dependent => :destroy

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/system/objs/images/:style/鮮乳坊簽名圖.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/controllers/admin/objs_controller.rb
class Admin::ObjsController < AdminApplicationController

  def index
    @objs = Obj.all.includes(:comments)
  end
end

app/controllers/objs_controller.rb
class ObjsController < ApplicationController
	before_action :authenticate_user!, :except => [:index]
	before_action :set_obj, :only => [:show, :edit, :update, :destroy]

	def post_index
		redirect_to objs_path(:page=>params[:page], :id=>params[:id], :order=>params[:order], :category_ids=>obj_params[:category_ids])
	end

	def index
		# objs = Obj.where('for obj filter')
		# objs = objs.includes('all you need associate')

		@categories = Category.all
		@user_likeship_arr = current_user.user_likeships.pluck(:obj_id) if current_user
		@objs = Obj.where(schedule_public: '1900-01-01 00:00:00')
		
		@objs = @objs.where([ "name like ?", "%#{params[:keyword]}%" ]) if params[:keyword]

		if current_user && current_user.admin?

			@objs = @objs.includes(:user).includes(:comments => :user)
		else
			@objs_read_only = @objs.where("access_authority = ?", 3)
			@objs_open_to_every_one = @objs.where("access_authority = ?", 4)
			if current_user
				# 文章可以設定權限：1. 只有自己可以看 2. 限好友才能看跟留言 3. 別人只能看不能留言 4. 別人可以看也能留言
				@objs_only_me = @objs.where("access_authority = ? and user_id = ?", 1, current_user.id )
				@objs_friends_only = @objs.where(:user_id => friends_arr).where('access_authority = ?',2)
				@objs = @objs_only_me.or(@objs_friends_only).or(@objs_read_only).or(@objs_open_to_every_one)
			else
				@objs = @objs_read_only.or(@objs_open_to_every_one)
			end

			@objs = @objs.includes(:user).where(:ispublic => true)
			@objs = @objs.includes(:public_comments => :user)
		end

		case params[:order]
		when "by_name"
			@objs = @objs.order('objs.name')
		when "by_newcomment"
			@objs = @objs.order('comments.id DESC').uniq
		when "by_hotest"
			# counter_cache(order_by_all_comments)
			@objs = @objs.order('objs.comments_count DESC')
		when "by_mostviewed"
			@objs = @objs.order('objs.views_count DESC')
		else
			@objs = @objs.order('objs.created_at')
		end

		if params[:category_ids]
			obj_catships_arr = ObjCategoryship.where(:category_id => params[:category_ids]).pluck(:obj_id).uniq
			@objs = @objs.where(:id => obj_catships_arr)
		end
		
		@objs = @objs.page(params[:page]).per(10)
		@objs = @objs.includes(:user_likeships).includes(:tags)

		if params[:id]
			@obj = Obj.find(params[:id])
		else
			@obj = Obj.new
		end
	end

	def new
		@obj = Obj.new
	end

	def show
		@obj.update(:views_count =>  @obj.views_count += 1)
		@obj_user_likeships = @obj.user_likeships.includes(:user)
		@obj_tags = @obj.tags
		@comments = @obj.comments.includes(:user) if @obj.comments
		@comment = @comments.where(:user => current_user).find_by_ispublic(false)
		@comment = Comment.new unless @comment
	end
 
	def editor
		@obj = Obj.find(params[:obj])
	end

	def create
		@obj = Obj.new(obj_params)
		@obj.user = current_user
		@obj.schedule_public = Time.now
		if @obj.save
			set_schedule
			@obj = Obj.new
			@success = true
		end
		render :form_template
	end

	def edit
		redirect_to objs_path(:page=>params[:page],:id=>params[:id])
	end

	def update
		if params[:del]
			@obj.image = nil
		end
		if @obj.update(obj_params)
			set_schedule
			flash[:notice] ="更新成功"
			redirect_to objs_path(:page=>params[:page])
		else
			render :form_template
		end
	end

	def destroy
		@obj.destroy
		flash[:alert] = "刪除成功"
		redirect_to objs_path(:page=>params[:page])
	end

	def about
		@objs = Obj.all
		@comments = Comment.all
		@users = User.all
		@tpconstructions = tpconstruction["result"]["results"]
	end

	private

	def set_obj
		@obj = Obj.find(params[:id])
	end
	def obj_params
		if params[:obj]
			params.require(:obj).permit(
				:name, :serial, :datebought, :dateretire, :value, :snumber1, :snumber2, 
				:string, :description, :text, :custodian, :keyword, :ispublic, :access_authority, :image, :category_ids => []
			)
		end
	end
	def tpconstruction
    url = "http://data.taipei/opendata/datalist/apiAccess?scope=resourceAquire&rid=201d8ae8-dffc-4d17-ae1f-e58d8a95b162"
    raw_data = JSON.parse(RestClient.get(url))
    return raw_data
  end
  def date_array(params_date_hash)
  	schedule_day = %w(1 2 3).map { |e| params_date_hash["schedule_public(#{e}i)"].to_i }.join('-')
  	schedule_time = %w(4 5).map { |e| params_date_hash["schedule_public(#{e}i)"].to_i }.join(':')
  	set_datetime = schedule_day + " " + schedule_time + ":00"
	end
	def set_schedule
		if params[:schedule_now]['{:checked=>false}'] == "1"
			set_datetime = date_array(params.to_unsafe_h[:obj])
			if Time.now + 3600 * 8 > set_datetime
				@obj.update(schedule_public: '1900-01-01 00:00:00')
			else
				@obj.update(schedule_public: set_datetime)
			end
		end
	end
	def friends_arr
		my_friends_arr = current_user.userships.pluck(:friend_id)
    added_me_arr = Usership.where(:friend_id => current_user.id).pluck(:user_id)
    friends_arr = added_me_arr & my_friends_arr
	end
end

app/helpers/admin/objs_helper.rb
module Admin::ObjsHelper
end

app/helpers/objs_helper.rb
module ObjsHelper
  def collected?(obj)
    return current_user.user_collectionships.find_by_obj_id(obj)
  end
  def subscribed?(obj)
    return current_user.user_subscribeships.find_by_obj_id(obj)
  end 
  def liked?(obj)
    if @user_likeship_arr
      return @user_likeship_arr.include? obj.id
    else
      return @user_likeship_arr
    end
  end
  def obj_link(obj)
    if obj.ispublic
      return obj_path(obj)
    else
      return editor_objs_path(:obj => obj)
    end
  end
  def index_name(obj)
    return simple_format("#{obj.name}\n( #{obj.description[0..20]}#{"..." if obj.description.length > 20} )", nil, :class => "text-left")
  end
end

app/views/objs/_comments.html.erb
<%= form_for comment, :url => "#" do |c| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= "(Draft)" unless comment.ispublic %>
      <div class="input-group">
        <span class="input-group-addon" id="basic-addon1"><%= user_name(comment.user) %></span>
        <span class="input-group-addon" id="basic-addon2">Title:</span>
        <%= c.text_field :title, :class => "form-control", :readonly => true, :style => "background-color:#fff" %>
        <% if comment.user == current_user %>
          <span class="input-group-btn" id="basic-addon3">
            <%= link_to "Del", user_comment_path(comment,:obj => @obj), :method=>"delete", :class =>"btn btn-danger", :remote => true %>
          </span>          
        <% end %>
      </div>
    </div>
    <div class="panel-body">
      <%= c.text_area :paragraph, :class => "form-control", :readonly => true, :style => "background-color:#fff" %>
    </div>
  </div>
<% end %>

app/views/objs/_comments_users.html.erb
<% if current_user.admin? %>
  <% obj.comments.collect{|comment| comment.user}.uniq.each do |obj_comment_user| %>
    <span class="label label-success">
      <%= link_to user_name(obj_comment_user), user_path(obj_comment_user), :class => "btn-link", :style => "color: white;" %> 
    </span>
  <% end %>
  <span class="label label-info">
    <%= obj.comments.size %>
  </span>
<% else %>
  <% obj.public_comments.collect{|comment| comment.user}.uniq.each do |obj_comment_user| %>
    <span class="label label-success">
      <%= link_to user_name(obj_comment_user), user_path(obj_comment_user), :class => "btn-link", :style => "color: white;" %> 
    </span>
  <% end %>
  <span class="label label-info">
    <%= obj.public_comments.size %>
  </span>
<% end %>

app/views/objs/_form_comment.html.erb
<%= form_for @comment, 
  :url => user_comments_path(:obj_id => @obj.id, :id => @comment), 
  :method => "post", :remote => true  do |f| %>

  <div class="panel panel-success">
    <div class="panel-heading">
      <div class="input-group">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button">Title:</button>
        </span>
        <%= f.text_field :title, :class => "form-control", :placeholder=> "Re: #{@obj.name}" %>
      </div>
    </div>
    
    <div class="panel-body">
      <%= f.text_area :paragraph, :class => "form-control" %>
    </div>

    <div class="panel-body">
      <div class="input-group">
        <%= f.submit "submit", :class => "btn btn-default text-right" %>
        <div class="checkbox btn btn-info" style="margin: 0 3px;">
          <label>
            <%= check_box_tag :ispublic, true %> Select to post
          </label>
        </div>
      </div>
    </div>
  </div>    
<% end %>

app/views/objs/_form_template.html.erb
<% content_for :head_js do %>
  <%= javascript_include_tag :form_template %>
<% end %>

<div class="panel panel-success">
<!-- Default panel contents -->
	<div class="panel-heading">
		<% if @obj.id %>
			<h1><%= @obj.name %></h1>
		<% else %>
			<h1>Add one more</h1>
		<% end %>
	</div>
	<div class="panel-body">
		<!-- Table -->
		<div class="col-md-12 ">
			<%= form_for @obj, :url => url, :method => method, :remote => true, :data => { :turbolinks => false } do |o| %>
				<ul class="pager">
					<% Category.all.each do |c| %>
						<li>
							<div class="col-md-3">
						    <div class="input-group">
						      <span class="input-group-addon">
						  			<%= check_box_tag "obj[category_ids][]", c.id, @obj.categories.map(&:id).include?(c.id) %>
						  		</span>
						  		<div class="form-control">
						  			<%= c.name %>
						  		</div>
						  	</div>
							</div>
						</li>
					<% end %>
					<%= hidden_field_tag 'obj[category_ids][]','' %>
				</ul>

				<dl class="dl-horizontal">
					<dt>
						<label class="text-capitalize text-right control-label">
							<h4><%= o.label :name, "name：" %></h4>
						</label>
					</dt>
					<dd>
						<p class="label label-danger col-md-7"><%= @obj.errors[:name][0] unless @obj.errors[:name].empty? %></p>
						<%= o.text_field :name, :class => "form-control", :placeholder=>"there MUST be a name"%>
					</dd>
				</dl>

				<dl class="dl-horizontal">
					<dt>
						<label class="text-capitalize text-right control-label">
							<h4>
								<%= o.label :serial, "serial：" %>
							</h4>
						</label>
					</dt>
					<dd>
						<p class="label label-danger col-md-7"><%= @obj.errors[:serial][0] unless @obj.errors[:serial].empty? %></p>
						<%= o.text_field :serial, :class => "form-control", :placeholder=>"Serial number ( MUST be unique )"%>
					</dd>
				</dl>

				<dl class="dl-horizontal">
					<dt>
						<label class="text-capitalize text-right control-label">
							<h4>
								<%= o.label :datebought, "datebought：" %>		
							</h4>
						</label>
					</dt>
					<dd>
						<p class="label label-danger col-md-7"><%= @obj.errors[:datebought][0] unless @obj.errors[:datebought].empty? %></p>
						<%= o.text_field :datebought, :class => "form-control", :placeholder=>"yyyy-mm-dd"%>
					</dd>
				</dl>

				<dl class="dl-horizontal">
					<dt>
						<label class="text-capitalize text-right control-label">
							<h4>
								<%= o.label :dateretire, "dateretire：" %>
							</h4>
						</label>
					</dt>
					<dd>
						<p class="label label-danger col-md-7"><%= @obj.errors[:dateretire][0] unless @obj.errors[:dateretire].empty? %></p>
						<%= o.text_field :dateretire, :class => "form-control", :placeholder=>"yyyy-mm-dd"%>
					</dd>
				</dl>

				<dl class="dl-horizontal">
					<dt>
						<label class="text-capitalize text-right control-label">
							<h4>
								<%= o.label :value, "value：" %>
							</h4>
						</label>
					</dt>
					<dd>
						<p class="label label-danger col-md-7"><%= @obj.errors[:value][0] unless @obj.errors[:value].empty? %></p>
						<%= o.text_field :value, :class => "form-control", :placeholder=>"price ( number only ! )"%>
					</dd>
				</dl>

				<dl class="dl-horizontal">
					<dt>
						<label class="text-capitalize text-right control-label">
							<h4><%= o.label :snumber1, "snumber1：" %></h4>
						</label>
					</dt>
					<dd>
						<p class="label label-danger col-md-7"><%= @obj.errors[:snumber1][0] unless @obj.errors[:snumber1].empty? %></p>
						<%= o.text_field :snumber1, :class => "form-control", :placeholder=>"S/N# number"%>
					</dd>
				</dl>

				<dl class="dl-horizontal">
					<dt>
						<label class="text-capitalize text-right control-label">
							<h4><%= o.label :snumber2, "snumber2：" %></h4>
						</label>
					</dt>
					<dd>
						<p class="label label-danger col-md-7"><%= @obj.errors[:snumber2][0] unless @obj.errors[:snumber2].empty? %></p>
						<%= o.text_field :snumber2, :class => "form-control", :placeholder=>"S/N# number"%>
					</dd>
				</dl>

				<dl class="dl-horizontal">
					<dt>
						<label class="text-capitalize text-right control-label">
							<h4><%= o.label :description, "description：" %></h4>
						</label>
					</dt>
					<dd>
						<p class="label label-danger col-md-7"><%= @obj.errors[:description][0] unless @obj.errors[:description].empty? %></p>
						<%= o.text_area :description ,:class => "form-control", :placeholder => "please give some description"%>
					</dd>
				</dl>

				<dl class="dl-horizontal">
					<dt>
						<label class="text-capitalize text-right control-label">
							<h4><%= o.label :custodian, "custodian：" %></h4>
						</label>
					</dt>
					<dd>
						<p class="label label-danger col-md-7"><%= @obj.errors[:custodian][0] unless @obj.errors[:custodian].empty? %></p>
						<%= o.text_field :custodian, :class => "form-control", :placeholder=>"custodian"%>
					</dd>
				</dl>

				<dl class="dl-horizontal">
					<dt>
						<label class="text-capitalize text-right control-label">
							<h4><%= o.label :ispublic, "Public：" %></h4>
						</label>
					</dt>
					<dd>
						<p class="label label-danger col-md-7"><%= @obj.errors[:ispublic][0] unless @obj.errors[:ispublic].empty? %></p>
						<div id="ispublic_check" class="checkbox  col-md-2">
							<label>
								<%= o.check_box :ispublic, {checked: false} %> Select to post
							</label>
						</div>
						<div id="select_access_authority" class="col-md-2 hidden" style="display: inline-block;line-height: 3rem;">
							<label>
								<%= o.select(:access_authority, [['only me', 1], ['friends only', 2], ['read only', 3], ['open to everyone', 4]]) %>
							</label>
						</div>
						<div class="col-md-2 text-right">
							<label class="text-capitalize">
								<h4 style="font-weight: bold;">image:</h4>
							</label>
						</div>
						<div class="col-md-6">
							<% o_file_field_margin = "margin: 10px 0;" %>
							<% if o.object.image.exists? %>
								<% o_file_field_margin = "margin: 0;" %>
				        <a href=<%= o.object.image.url %>>
				          <%= image_tag o.object.image.url(:medium) %>
				        </a>
				        <div class="chechbox">
				        	<label>
				        		<%= check_box_tag :del %> Delete this image 
				        	</label>
				        </div>
				        <p>or update another one.</p>
							<% end %>
							<label>
								<%= o.file_field :image, :style=>o_file_field_margin %>
							</label>							
						</div>
					</dd>
				</dl>
				
				<dl id="ispublic_schedule" class="dl-horizontal hidden">
					<dt>
						<label class="text-capitalize text-right control-label">
							<h4><%= o.label :schedule_public, "Schedule：" %></h4>
						</label>
					</dt>
					<dd>
						<div id="schedule_now" class="checkbox col-md-2">
							<label>
								<%= check_box :schedule_now, :checked => false %> Set Schedule
							</label>
						</div>
						<div id="schedule_time" class="hidden" style="display: inline-block;line-height: 3rem;">
							<label class="control-label">
								<%= o.datetime_select :schedule_public, selected: Time.now, :start_year => Time.now.year, :end_year => Time.now.year + 2 %>
							</label>
						</div>
					</dd>
				</dl>
				<%= o.submit :class => "btn btn-success col-md-2"%>
			<% end %>
				<p class="col-md-2"></p>
				<h4><p class="label label-success col-md-2"><%= "Create Success" if @success %></p></h4>
		</div>
	</div>
</div>

app/views/objs/_navbar.html.erb
<% friend_link_class = "" %>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "Dopamine", objs_path, :class => "navbar-brand", data: { turbolinks: false } %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to "about", about_objs_path %>
        </li>
      </ul>
      <div class="nav navbar-form  navbar-left">
        <div class="fb-like btn" data-href="http://localhost:3000/" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
      </div>
      <div class="nav navbar-form navbar-left" style="padding-left: 0;padding-right: 0;">
        <div class="form-group">
          <%= form_tag objs_path, :method => :get do %>
            <%= text_field_tag "keyword", nil,:class => "form-control" %>
            <%= submit_tag "Search", name: nil, :class => "btn btn-default" %>
          <% end %>
        </div>
      </div>
      <ul class="nav navbar-nav navbar-right">        
        <% if current_user %>
          <% friend_link_class = "glyphicon glyphicon-envelope" if current_user.have_new_friend? %>
          <li>
            <%= link_to "Friends", show_friends_users_path, 
            :class => friend_link_class, data: { turbolinks: false } %>
          </li>
          <li><%= link_to "Now you see me", admin_users_path if current_user.admin? %></li>
          <li><%= link_to "Edit profile", edit_registration_path(:user) %></li>
          <li><%= link_to "Log out", destroy_user_session_path, :method => "delete" %></li>
        <% else %>
          <li><%= link_to "Sign up", new_registration_path(:user) %></li>
          <li><%= link_to "Sign in", new_session_path(:user) %></li>
          <li><%= link_to "FB Sign in", user_facebook_omniauth_authorize_path %></li>
        <% end %>
        <li>
          <img src=<%= avatar_url %> alt="avatar" style="margin: 8px 12px; width: 32px;">
        </li>
        <li><%= link_to user_name(current_user), current_user ? user_path(current_user) : "#" %></li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/objs/edit_obj.html.erb
<%= render :partial =>"form_template" ,:locals => {:url => obj_path(@obj,:page=>params[:page]), :method => "patch"}  %>

app/views/objs/editor.html.erb
<%= render :partial =>"form_template" ,:locals => {:url => obj_path(@obj), :method => "patch"}  %>

app/views/objs/form_template.js.erb
var content = "<%=j render(:partial => 'form_template', :locals => {:url => objs_path(:page => params[:page]), :method => 'post' }) %>"
$('#form_template').html(content);
$('#ispublic_check').on('change', function(){
  $('#ispublic_schedule').toggleClass('hidden');
  $('#select_access_authority').toggleClass('hidden');
});
$('#schedule_now').on('change', function(){
  $('#schedule_time').toggleClass('hidden');
});

app/views/objs/index.html.erb
<% content_for :head_css do %>
  <%= stylesheet_link_tag :objs %>
<% end %>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">
  	<h1>Property List</h1>
  </div>
  <div class="panel-body">
    <%= form_tag post_index_objs_path(:order => params[:order]) do %>
      <% @categories.each do |c| %>
        <% checkinclude = params[:category_ids].include?(c.id.to_s) if params[:category_ids] %>
        <div class="form-group">
          <div class="pull-left">
            <label for=<%="obj_category_ids_#{c.id}"%> >
              <div class="checkbox btn btn-default" style="margin: 0 3px;" >
                <label>
                  <%= check_box_tag "obj[category_ids][]", c.id, checkinclude, :id => "obj_category_ids_#{c.id}" %>
                  <%= c.name %>
                </label>
              </div>
            </label>
          </div>
        </div>
      <% end %>
      <div class="form-group pull-right">
        <%= submit_tag "apply", :class => "btn btn-primary" %>
      </div>
      <%= hidden_field_tag 'obj[category_ids][]','' %>
    <% end %>
  </div>
  <!-- Table -->
  <table class="table table-hover">
		<tr>
			<th>
        <h4 class="navbar-left">Sort by</h4>
        <ul class="nav nav-pills navbar-right">
          <li role="presentation" <%= "class=active" if params[:order] == "by_newest" %>>
            <a href=<%= objs_path(:order => "by_newest", :page=>params[:page]) %>>Default</a>
          </li>
          <li role="presentation" <%= "class=active" if params[:order] == "by_name" %>>
            <a href=<%= objs_path(:order => "by_name",:page=>params[:page]) %>>Alphabet</a>
          </li>
          <li role="presentation" <%= "class=active" if params[:order] == "by_newcomment" %>>
            <a href=<%= objs_path(:order => "by_newcomment",:page=>params[:page]) %>>NewComment</a>
          </li>
          <li role="presentation" <%= "class=active" if params[:order] == "by_hotest" %>>
            <a href=<%= objs_path(:order => "by_hotest",:page=>params[:page]) %>>Hotest</a>
          </li>
          <li role="presentation" <%= "class=active" if params[:order] == "by_mostviewed" %>>
            <a href=<%= objs_path(:order => "by_mostviewed",:page=>params[:page]) %>>MostViewed</a>
          </li>
        </ul>
      </th>
      <% if current_user %>
        <th class="text-center"><h4>Like</h4></th>
        <th class="text-center"><h4>Edit</h4></th>
        <th class="text-center"><h4>Delete</h4></th>
      <% end %>
		</tr>
		<% @objs.each do |obj| %>
      <% @obj_tags = obj.tags %>
			<tr>
				<td>
          <div class="pull-right">
            <%= render :partial =>"comments_users", :locals => {:obj => obj } if current_user %>
            <span class="badge"><%= obj.views_count %></span> 
          </div>
          <%= link_to index_name(obj), obj_path(obj), :class => "text-left btn-link col-md-4", data: { turbolinks: false } %>  
          <div id="tags">
            <%= render :partial =>"/tags/tags" %>
          </div>          
        </td>
        <% if current_user %>
          <td id="like_star_<%= obj.id %>" class="text-center">
            <%= render :partial => "/users/like", :locals => { :obj => obj } %>
          </td>
          <% if current_user.access?(obj) %>
            <td class="text-center">
              <%= link_to "Edit", edit_obj_path(obj,:page=>params[:page]),  :class => "btn btn-default", data: { turbolinks: false } %>
            </td>
            <td class="text-center">
              <%= link_to "Delete", obj_path(obj,:page=>params[:page]),:method => :delete, :class => "btn btn-danger"%>
            </td>
          <% else %>
            <td></td>
            <td></td>
          <% end %>
			  <% end %>
      </tr>
		<% end %>
	</table>
</div>

<% if current_user %>
  <% if @obj.new_record? %>
    <div id="form_template" class="hidden">
      <%= render :partial =>"form_template" ,:locals => {:url => objs_path(:page=>params[:page]), :method => "post" } %>
    </div>
    <div id="new_obj_btn" class="pull-right btn btn-primary">
      New an Obj
    </div>
  <% else %>
    <%= render :partial =>"form_template" ,:locals => {:url => obj_path(@obj,:page=>params[:page]), :method => "patch"}  %>
  <% end %>
<% end %>

<div data-turbolinks="false">
  <%= paginate @objs %>
</div>

app/views/objs/index.js.erb
var content = "<%=j render(:partial => 'form_template', :locals => {:url => objs_path(:page => params[:page]), :method => 'post' }) %>"
$('#form_template').html(content);
$('#ispublic_check').on('change', function(){
  $('#ispublic_schedule').toggleClass('hidden');
});

app/views/objs/obj_editor.html.erb
<%= render :partial =>"form_template" ,:locals => {:url => obj_path(@obj,:page=>params[:page]), :method => "patch"}  %>