config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => "/cable"

  namespace :admin do
    resources :users
    resources :objs
    resources :categories
  end


  # namespace :api, path: 'somthing' do => /something => api::xxx
  namespace :api, path: '' do
    constraints(host: 'api.localhost') do
      resources :users
    end
  end  

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    collection do
      get :edit_collection
      get :edit_like
      get :edit_subscribe
      get :edit_friendship
      get :show_friends
    end
  end

  resources :user_comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "objs#index"

  resources :objs do
    collection do
      post :post_index 
      get :editor
      get :about
    end
  end

  resources :tags
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates_presence_of :name

  has_many :objs, :through => :obj_tagships
  has_many :obj_tagships, :dependent => :destroy
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def show
    @tag = Tag.find(params[:id])
    tags_arr = Tag.where(:name => @tag.name).ids
    obj_arr = ObjTagship.where(:id => tags_arr).pluck(:obj_id).uniq
    @objs = Obj.where(:id => obj_arr).includes(:tags)
  end

  def create
    unless tag_name.empty?
      @tags = Obj.find(params[:obj]).tags
      if @tags.find_by_name(tag_name)
        params[:tag][:name] = ""
      else
        @tag = @tags.create(:name => tag_name)
      end 
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    respond_to do |format|
      format.js
    end
  end

  private
  def tag_name
    params[:tag][:name]
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_new_tag.html.erb
<%= form_for Tag.new, :url => tags_path(:obj => @obj), :remote => true do |f|%>
  <div class="input-group pull-right">
    <span class="" id="tag_fold_buttun">
      <div class="btn btn-default glyphicon glyphicon-console pull-right" style="top: 0;font-weight: bold;"></div>
    </span>
    <%= f.text_field :name, :id => "tag_input", :class => "form-control hidden" %>
    <span class="input-group-btn hidden" id="tag_create_buttun">
      <%= f.submit "add", :class =>"btn btn-success" %>
    </span>
  </div>
<% end %>

app/views/tags/_tags.html.erb
<% @obj_tags.each do |tag| %>
  <%= link_to "##{tag.name}", tag_path(tag), :class=>"btn btn-link" %>
<% end %>

app/views/tags/create.js.erb
$('#tags').append(' <%= link_to "##{@tag.name}", tag_path(@tag), :class=>"btn btn-link", :style=>"padding: 0;" if @tag %>');
$('#tag_input').val('');
$('#tags').find('a').attr({'data-method':'get', 'class':'btn btn-link'});

app/views/tags/destroy.js.erb
$('#tags a[href$="/<%=@tag.id%>"]').remove();

app/views/tags/show.html.erb
<% @objs.each do |obj| %>
<tr>
  <th>
    <%= link_to obj.name, obj_path(obj), :class=>"btn btn-link", data: { turbolinks: false }  %>  
  </th>
  <td>
    <% obj.tags.each do |tag| %>
      <%= tag.name %>
    <% end %>
  </td>
</tr>
<br>
<% end %>